- name: Configure /etc/hosts for all managed hosts
  hosts: all
  tasks:
  - name: Add all hosts to /etc/hosts of all servers
    lineinfile:
        line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item]['ansible_fqdn'] }} {{ hostvars[item]['ansible_hostname'] }}"
        path: /etc/hosts
        state: present
    loop: "{{ groups['all'] }}"
  - name: Remove 127.0.1.1 entry from /etc/hosts
    lineinfile:
      path: /etc/hosts
      regexp: '^127\.0\.1\.1'
      state: absent

- name: Configure /etc/hosts for localhost
  hosts: localhost
  tasks:
  - name: Add all hosts to /etc/hosts of all servers
    lineinfile:
        line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item]['ansible_fqdn'] }} {{ hostvars[item]['ansible_hostname'] }}"
        path: /etc/hosts
        state: present
    loop: "{{ groups['all'] }}"
