- name: Configure /etc/hosts for all managed hosts
  hosts: all
  tasks:
  - name: Remove existing entries for walman hosts from /etc/hosts on managed hosts
    lineinfile:
      regexp: "walmandb"
      path: /etc/hosts
      state: absent
  - name: Add all hosts to /etc/hosts of all servers
    lineinfile:
        line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item]['ansible_fqdn'] }} {{ hostvars[item]['ansible_hostname'] }}"
        path: /etc/hosts
        state: present
    loop: "{{ groups['all'] }}"

- name: Configure /etc/hosts for localhost
  hosts: localhost
  tasks:
  - name: Remove existing entries for walman hosts from /etc/hosts on localhost
    lineinfile:
      regexp: "walmandb"
      path: /etc/hosts
      state: absent
  - name: Add all hosts to /etc/hosts of all servers
    lineinfile:
        line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item]['ansible_fqdn'] }} {{ hostvars[item]['ansible_hostname'] }}"
        path: /etc/hosts
        state: present
    loop: "{{ groups['all'] }}"
