- name: Gather facts for all hosts
  hosts: all
  tasks:
  - name: Gather the facts
    setup:

- name: Generate local ssh keypairs for all hosts
  hosts: localhost
  become: false
  tasks:
  - name: Generate local directory for each host
    file:
      name: "/tmp/ssh_keys/{{ hostvars[item]['ansible_hostname'] }}"
      state: directory
    loop: "{{ groups['all'] }}"
  - name: Generate openssh keypairs
    openssh_keypair:
      path: "/tmp/ssh_keys/{{ hostvars[item]['ansible_hostname'] }}/id_rsa"
    loop: "{{ groups['all'] }}"

- name: Configure ssh between all hosts for oracle user
  hosts: all
  tasks:
  - name: Copy the ssh key pair to each respective host
    copy:
      src: "/tmp/ssh_keys/{{ ansible_hostname }}/"
      dest: "/home/oracle/.ssh/"
      owner: oracle
      group: oinstall
      mode: '0600'
  - name: Deploy the ssh public keys to all hosts
    authorized_key:
      key: "{{ lookup('file', '/tmp/ssh_keys/{{ hostvars[item][\"ansible_hostname\"] }}/id_rsa.pub') }}"
      user: oracle
      state: present
    loop: "{{ groups['all'] }}"
  - name: Configure known_hosts for FQDNs
    become_user: oracle
    lineinfile:
      line: "{{ lookup('pipe', 'ssh-keyscan -t rsa,ed25519 {{ hostvars[item][\"ansible_fqdn\"] }}') }}"
      dest: /home/oracle/.ssh/known_hosts
      create: true
      state: present
    loop: "{{ groups['all'] }}"
  - name: Configure known_hosts for short hostnames
    lineinfile:
      line: "{{ lookup('pipe', 'ssh-keyscan -t rsa,ed25519 {{ hostvars[item][\"ansible_hostname\"] }}') }}"
      dest: /home/oracle/.ssh/known_hosts
      state: present
    loop: "{{ groups['all'] }}"
  - name: Configure known_hosts for IP Addresses
    lineinfile:
      line: "{{ lookup('pipe', 'ssh-keyscan -t rsa,ed25519 {{ hostvars[item][\"ansible_default_ipv4\"][\"address\"] }}') }}"
      dest: /home/oracle/.ssh/known_hosts
      state: present
    loop: "{{ groups['all'] }}"

  - name: Test ssh connection to each other server
    become_user: oracle
    shell:
      cmd: "ssh -o StrictHostKeyChecking=accept-new oracle@{{ hostvars[item]['ansible_fqdn'] }} 'hostname'"
    loop: "{{ groups['all'] }}"
    register: ssh_test_results
  - name: Show ssh test results
    debug:
      msg: "item['item'] = {{ item['item'] }}, item['stdout'] = {{ item['stdout'] }}"
    loop: "{{ ssh_test_results['results'] }}"
